CREATE FUNCTION
   MRF_PROCESS(PM_KEY1 STRING, PM_KEY2 STRING, PM_KEY3 STRING )
   COMMENT 'Processing Pkgs'
   RETURNS STRING
   AS
   $$
        SELECT FIRST(name)
        FROM MOC
        WHERE PM_GROUP_KEY1 = PM_KEY1 AND PM_KEY2=PM_GROUP_KEY2 AND PM_KEY3 = PM_GROUP_KEY3
   $$ LANGUAGE SQL;